In [1]:
from model import Classifier
import tensorflow as tf
from transformers import AutoTokenizer

In [2]:
model = Classifier()

2021-08-19 12:50:23.190922: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcuda.so.1
2021-08-19 12:50:23.214035: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-08-19 12:50:23.214422: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1733] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce RTX 2080 Ti computeCapability: 7.5
coreClock: 1.545GHz coreCount: 68 deviceMemorySize: 10.76GiB deviceMemoryBandwidth: 573.69GiB/s
2021-08-19 12:50:23.214437: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
2021-08-19 12:50:23.215834: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcublas.so.11
2021-08-19 12:50:23.215856: I tensorflow/stream_executor/platfo

In [ ]:
tokenizer = AutoTokenizer.from_pretrained('hfl/chinese-electra-small-ex-discriminator')

In [3]:
model_dir = 'model'

latest_ckpt = tf.train.latest_checkpoint(model_dir)
latest_ckpt

'model/model.ckpt-10'

In [4]:
model.load_weights(latest_ckpt).expect_partial()

In [10]:
sent = '这是一篇关于环保的文章'
inputs = tokenizer(sent, return_tensors='tf')
model(inputs, training=False)

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-0.40609637,  0.46968406]], dtype=float32)>

In [11]:
sent = '法制很重要'
inputs = tokenizer(sent, return_tensors='tf')
model(inputs, training=False)

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[ 0.33006904, -0.36777768]], dtype=float32)>

In [12]:
sent = '当代环境保护法则'
inputs = tokenizer(sent, return_tensors='tf')
model(inputs, training=False)

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-0.6116645,  0.6652166]], dtype=float32)>